name: Test Package Publish

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  publish-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install versioner
        env:
          NPM_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        run: >
          echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" > ~/.npmrc &&
          echo "@answerbook:registry=https://npm.pkg.github.com/" >> ~/.npmrc &&
          git config user.name "LogDNA Bot" &&
          git config user.email "bot@logdna.com" &&
          git config remote.origin.url "https://${GITHUB_ACTOR}:${NPM_TOKEN}@github.com/${GITHUB_REPOSITORY}" &&
          npm install -g @answerbook/versioner
      - run: npm install
      - run: versioner --publish --dry
